#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


set -eu

tee /etc/modules-load.d/kubernetes.conf <<EOF
overlay
br_netfilter
EOF
tee /etc/sysctl.d/kubernetes.conf <<EOF
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

# this is based on https://v1-27.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm

K8S_VERSION=${K8S_VERSION%-*}  # remove the -... suffix
K8S_XY_VERSION=${K8S_VERSION%.*}  # remove the .z in x.y.z

# Support only Debian style distro
if [[ ${DISTRO_NAME} =~ (ubuntu|debian) ]]; then

	curl -fsSL https://pkgs.k8s.io/core:/stable:/v${K8S_XY_VERSION}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
	echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v${K8S_XY_VERSION}/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

	apt update

	apt -y install containerd
	mkdir -p /etc/containerd
	containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | tee /etc/containerd/config.toml

	apt install -y kubelet=$K8S_VERSION-* kubeadm=$K8S_VERSION-* kubectl=$K8S_VERSION-*
fi

# Support only SuSE OSs
if [[ ${DISTRO_NAME} =~ (opensuse|sle) ]]; then

	# Vars
	ARCH="amd64"
	CNI_DEST="/opt/cni/bin"
	KUBEADM_DIR="/usr/local/bin"
	CNI_PLUGINS_VERSION="v1.3.0"
	CRICTL_VERSION="v$K8S_XY_VERSION.0"
	RELEASE_VERSION="v0.15.1"

	zypper install -y containerd
	mkdir -p /etc/containerd
	containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | tee /etc/containerd/config.toml
	systemctl enable containerd.service

	# Install CNI plugins
	mkdir -p "$CNI_DEST"
	curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-${ARCH}-${CNI_PLUGINS_VERSION}.tgz" | tar -C "$CNI_DEST" -xz

	# Install CRICTL align to the K8S version
	curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCH}.tar.gz" | tar -C $KUBEADM_DIR -xz

	# Install kubeadm, kubelet, kubectl and kubelet systemd service
	curl -L --remote-name-all --output-dir $KUBEADM_DIR https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/${ARCH}/{kubeadm,kubelet,kubectl}
	chmod +x $KUBEADM_DIR/{kubeadm,kubelet,kubectl}
	curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:${KUBEADM_DIR}:g" | tee /etc/systemd/system/kubelet.service
	mkdir -p /etc/systemd/system/kubelet.service.d
	curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${KUBEADM_DIR}:g" | tee /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
	systemctl enable kubelet.service
fi
