export DIB_CLOUD_INIT_SYLVA_GROUP=${DIB_CLOUD_INIT_SYLVA_GROUP:-sylva}
export DIB_CLOUD_INIT_DEFAULT_USERNAME=${DIB_CLOUD_INIT_DEFAULT_USERNAME:-node-admin}
export DIB_GRUB_TIMEOUT=${DIB_GRUB_TIMEOUT:-0}