#!/bin/bash

### Install a newer version of ansible which is not available for Ubuntu Jammy
apt update
apt install software-properties-common -y
apt install gpg-agent -y
add-apt-repository --yes --update ppa:ansible/ansible
apt install ansible -y
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

cat > /tmp/requirements.yml <<EOF
roles:
  - name: UBUNTU22-CIS
    scm: git
    src: https://github.com/ansible-lockdown/UBUNTU22-CIS
    version: "V1.0.0"
EOF

cat > /tmp/site.yml <<EOF
---
- hosts: localhost
  become: true
  vars:
      is_container: false
      ubtu22cis_is_router: true 
      ubtu22cis_time_sync_tool: chrony
      ubtu22cis_ipv6_required: true
      ubtu22cis_install_network_manager: false
      ubtu22cis_system_is_log_server: false
      ubtu22cis_firewall_package: ufw
      ubtu22cis_time_synchronization_servers:
        - 172.20.4.108
      ubtu22cis_rsyslog_ansible_managed: false
      ubtu22cis_logrotate_create_settings: "0640 syslog adm"
      ubtu22cis_sshd:
        log_level: "INFO"
        max_auth_tries: 4
        ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
        macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
        kex_algorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
        client_alive_interval: 300
        client_alive_count_max: 0
        login_grace_time: 60
        max_sessions: 4
        allow_users: ""
        allow_groups: ""

  roles:
  - { role: UBUNTU22-CIS, ignore_errors: yes, tags: ['hardening'] }
  
  tasks: 
   - name: remove config file from uninstalled package telnet
     ansible.builtin.package:
      name: telnet
      purge: yes
      state: absent
   
   - name: remove config file from uninstalled package rsync
     ansible.builtin.package:
      name: rsync
      purge: yes
      state: absent
      
   - name: fix ClientAliveCountMax
     command: sed -i -e 's/ClientAliveCountMax 0/ClientAliveCountMax 3/' /etc/ssh/sshd_config

   - name: fix core dumps size
     copy:
      dest: "/etc/security/limits.d/00-core-dumps"
      content: '* hard core 0'
EOF

ufw allow out from any to any  comment "allow all out"
ansible-galaxy install -r /tmp/requirements.yml
ansible-playbook /tmp/site.yml --skip-tags="rule_3.5.3.2.3,rule_4.2.1.5"

sysctl --system
sed -i "s/^UMASK.*/UMASK 027/g" /etc/login.defs
sed -i "/umask/d" /etc/login.defs
echo "session optional  pam_mkhomedir.so  umask=0027" |sudo tee -a  /etc/pam.d/common-session

### Cleanup
apt remove --purge  ansible perl gcc strace ltrace -y
rm -rf /tmp/requirements.yml /tmp/site.yml ~/.ansible
apt autoremove -y
