---

workflow:
  rules:
    - when: always
variables:
  REPO_URL: "oci://$CI_REGISTRY_IMAGE"
  IMAGE_FORMAT: qcow2

stages:
  - test
  - "build hardened image"
  - "build plain image"

include:
  - project: 'renovate-bot/renovate-runner'
    ref: v16.2.1
    file: '/templates/renovate-config-validator.gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          paths:
            - .gitlab-ci.yml
            - renovate.json
  - project: 'sylva-projects/sylva-elements/renovate'
    ref: 1.0.0
    file: '/templates/renovate-dry-run.gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          paths:
            - renovate.json

build-hardened:
  stage: "build hardened image"
  tags:
    - oro-libvirt
  before_script:
    - curl -O http://ports.ubuntu.com/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb
    - sudo dpkg -i debootstrap_1.0.126+nmu1_all.deb
    - sudo apt install zstd -y
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder --break-system-packages
    - python3 -m pip install --user . --break-system-packages
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b cis_remediation -b lvm -b rke2_airgapped --format ${IMAGE_FORMAT} -o ubuntu-22.04-hardened.${IMAGE_FORMAT}
    - md5sum=$(md5sum ubuntu-22.04-hardened.${IMAGE_FORMAT} | awk '{ print $1 }')
    - sha256sum=$(sha256sum ubuntu-22.04-hardened.${IMAGE_FORMAT} | awk '{ print $1 }')
    - |
      echo -n "md5sum: $md5sum\nsha256sum: $sha256sum"
    - flux push artifact $REPO_URL/diskimage-builder-hardened:$(git tag --points-at HEAD) --timeout 2h --path="ubuntu-22.04-hardened.${IMAGE_FORMAT}" --source="$(git config --get remote.origin.url)" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD --annotations sylvaproject.org/diskimage/sha256=$sha256sum --annotations=sylvaproject.org/diskimage/md5=$md5sum
  only:
    - tags

build-plain:
  stage: "build plain image"
  tags:
    - oro-libvirt
  before_script:
    - curl -O http://ports.ubuntu.com/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb
    - sudo dpkg -i debootstrap_1.0.126+nmu1_all.deb
    - sudo apt install zstd -y
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder --break-system-packages
    - python3 -m pip install --user . --break-system-packages
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b rke2_airgapped -o ubuntu-22.04-plain.${IMAGE_FORMAT}
    - md5sum=$(md5sum ubuntu-22.04-plain.${IMAGE_FORMAT} | awk '{ print $1 }')
    - sha256sum=$(sha256sum plain-22.04-hardened.${IMAGE_FORMAT} | awk '{ print $1 }')
    - |
      echo -n "md5sum: $md5sum\nsha256sum: $sha256sum"
    - flux push artifact $REPO_URL/diskimage-builder-plain:$(git tag --points-at HEAD) --timeout 2h --path="ubuntu-22.04-plain.${IMAGE_FORMAT}" --source="$(git config --get remote.origin.url)" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD --annotations sylvaproject.org/diskimage/sha256=$sha256sum --annotations=sylvaproject.org/diskimage/md5=$md5sum
  only:
    - tags
