---

workflow:
  rules:
    - when: always
variables:
  REPO_URL: "oci://$CI_REGISTRY_IMAGE"
  IMAGE_FORMAT: qcow2
  IMAGE_FLAVOR: ""
  IMAGE_FILENAME: ubuntu-22.04-${IMAGE_FLAVOR}.${IMAGE_FORMAT}
  ARTIFACT_NAME: diskimage-builder-ubuntu-22.04-${IMAGE_FLAVOR}-${IMAGE_FORMAT}

stages:
  - build
  - test

include:
  - project: 'renovate-bot/renovate-runner'
    ref: v16.2.1
    file: '/templates/renovate-config-validator.gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          paths:
            - .gitlab-ci.yml
            - renovate.json
  - project: 'sylva-projects/sylva-elements/renovate'
    ref: 1.0.0
    file: '/templates/renovate-dry-run.gitlab-ci.yml'
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          paths:
            - renovate.json

.build-image:
  stage: build
  tags:
    - oro-libvirt
  before_script:
    - curl -O http://ports.ubuntu.com/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb
    - sudo dpkg -i debootstrap_1.0.126+nmu1_all.deb
    - sudo apt install zstd -y
  script:
    - date
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder --break-system-packages
    - python3 -m pip install --user . --break-system-packages
    #- kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b cis_remediation -b lvm -b rke2_airgapped --format ${IMAGE_FORMAT} -o ${IMAGE_FILENAME}    ### FIXME
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b cis_remediation -b lvm --format ${IMAGE_FORMAT} -o ${IMAGE_FILENAME}
    - date
    - md5sum=$(md5sum ${IMAGE_FILENAME} | awk '{ print $1 }')
    - date
    - sha256sum=$(sha256sum ${IMAGE_FILENAME} | awk '{ print $1 }')
    - date
    - |
      echo -e "md5sum: $md5sum\nsha256sum: $sha256sum"
    - flux push artifact $REPO_URL/${ARTIFACT_NAME}:$(git tag --points-at HEAD) --timeout 2h --path="${IMAGE_FILENAME}" --source="${CI_REPOSITORY_URL/gitlab-ci-token*@/}" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD --annotations sylvaproject.org/diskimage/sha256=$sha256sum --annotations=sylvaproject.org/diskimage/md5=$md5sum
    - date
  # only:
  #   - tags
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual

build-hardened-qcow2:
  extends: .build-image
  variables:
    IMAGE_FLAVOR: hardened
    IMAGE_FORMAT: qcow2

build-plain-qcow2:
  extends: .build-image
  variables:
    IMAGE_FLAVOR: plain
    IMAGE_FORMAT: qcow2

build-plain-raw:
  extends: .build-image
  variables:
    IMAGE_FLAVOR: plain
    IMAGE_FORMAT: raw
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder --break-system-packages
    - python3 -m pip install --user . --break-system-packages
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b cis_remediation -b lvm -b rke2_airgapped --format ${IMAGE_FORMAT} -o ${IMAGE_FILENAME}    ### FIXME
    - date
    - md5sum=$(md5sum ${IMAGE_FILENAME} | awk '{ print $1 }')
    - date
    - sha256sum=$(sha256sum ${IMAGE_FILENAME} | awk '{ print $1 }')
    - date
    - |
      echo -e "md5sum: $md5sum\nsha256sum: $sha256sum"
    - ls -l ${IMAGE_FILENAME}
    - date
    - gzip --fast ${IMAGE_FILENAME}
    - date
    - ls -l ${IMAGE_FILENAME}*
    - flux push artifact $REPO_URL/${ARTIFACT_NAME}:$(git tag --points-at HEAD) --timeout 2h --path="${IMAGE_FILENAME}.gz" --source="${CI_REPOSITORY_URL/gitlab-ci-token*@/}" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD --annotations sylvaproject.org/diskimage/sha256=$sha256sum --annotations=sylvaproject.org/diskimage/md5=$md5sum --disable-compression
    - date
