variables:
  REPO_URL: "oci://$CI_REGISTRY_IMAGE"

stages:
  - "build plain image"

build-plain:
  stage: "build plain image"
  tags:
    - oro-libvirt
  before_script:
    - curl -O http://ports.ubuntu.com/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb
    - sudo dpkg -i debootstrap_1.0.126+nmu1_all.deb
    - sudo apt install zstd -y
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder
    - python3 -m pip install --user .
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -o ubuntu-22.04-plain.qcow2
    - sha256sum ubuntu-22.04-plain.qcow2 | awk '{ print $1 }'
    - flux push artifact $REPO_URL/diskimage-builder-plain:$(git tag --points-at HEAD) --timeout 15m --path="ubuntu-22.04-plain.qcow2" --source="$(git config --get remote.origin.url)" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $GITLAB_USER_LOGIN:$REPO_TOKEN
  only:
    - tags
