variables:
  REPO_URL: "oci://$CI_REGISTRY_IMAGE"

stages:
  - build

.config_build:
  stage: build
  tags:
    - oro-libvirt
  before_script:
    - curl -O http://ports.ubuntu.com/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb
    - sudo dpkg -i debootstrap_1.0.126+nmu1_all.deb
    - sudo apt install zstd -y
  script:
    - export PATH="${HOME}/.local/bin:${PATH}"
    - pip3 install diskimage-builder
    - python3 -m pip install --user .
    - kanod-image-builder -s target=ubuntu -s release=jammy -b no_kanod_network -b cis_remediation -b lvm -o $DISK_IMAGE_NAME
    - sha256sum $DISK_IMAGE_NAME | awk '{ print $1 }'
    - flux push artifact $REPO_URL/$DISK_IMAGE_TYPE:$(git tag --points-at HEAD) --timeout 30m --path="$DISK_IMAGE_NAME" --source="$(git config --get remote.origin.url)" --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD
  only:
    - tags

build-plain:
  extends: 
  - .config_build
  variables:
    DISK_IMAGE_NAME: ubuntu-22.04-plain.qcow2
    DISK_IMAGE_TYPE: diskimage-builder-plain

build-hardened:
  extends: 
  - .config_build
  variables:
    DISK_IMAGE_NAME: ubuntu-22.04-hardened.qcow2
    DISK_IMAGE_TYPE: diskimage-builder-hardened
