#!/bin/bash

GRUB_ADMIN_PASSWORD=${GRUB_ADMIN_PASSWORD:-}
GRUB_ADMIN_USERNAME=admin

_GRUB_PASSWORD_FILE=/etc/grub.d/01_password

if [ "$EUID" -ne 0 ]; then 
	echo "Please run as root"
  	exit 1
fi

if [ "x${GRUB_ADMIN_PASSWORD}" = "x" ]; then
	echo "No password detected"
	exit 2
fi

# Generate grub password in memory
_grub_password=$(echo -e "${GRUB_ADMIN_PASSWORD}\n${GRUB_ADMIN_PASSWORD}" | LC_ALL=C /usr/bin/grub-mkpasswd-pbkdf2 | awk '/hash of / {print $NF}')

# Write grub password file content
echo "#!/bin/sh" > ${_GRUB_PASSWORD_FILE}
echo "set -e" >> ${_GRUB_PASSWORD_FILE}
echo "cat << EOF" >> ${_GRUB_PASSWORD_FILE}
echo "set superusers=\"${GRUB_ADMIN_USERNAME}\"" >> ${_GRUB_PASSWORD_FILE}
echo "password_pbkdf2 ${GRUB_ADMIN_USERNAME} ${_grub_password}" >> ${_GRUB_PASSWORD_FILE}
echo "EOF" >> ${_GRUB_PASSWORD_FILE}

# Set proper privileges
chmod 755 ${_GRUB_PASSWORD_FILE}

# Set unrestricted for the boot sequence
sed -i 's/CLASS="--class gnu-linux --class gnu --class os"/CLASS="--class gnu-linux --class gnu --class os --unrestricted"/g' /etc/grub.d/10_linux

# Update grub configuration
update-grub
