#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Create the local-path-provisioner folders
mkdir -p /var/lib/kubelet/local-path-provisioner /opt/local-path-provisioner

# Add the bind mount in fstab
echo "/var/lib/kubelet/local-path-provisioner /opt/local-path-provisioner none defaults,bind 0 0" >> /etc/fstab
