#!/bin/bash

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"


SEARCH_GRUB_PARAMS=("GRUB_TIMEOUT" "GRUB_CMDLINE_LINUX_DEFAULT" "GRUB_CMDLINE_LINUX")

cp /etc/default/grub /etc/default/grub.orig

for i in ${!SEARCH_GRUB_PARAMS[@]};
do
  # Get string we want to search
  GRUB_PARAM="${SEARCH_GRUB_PARAMS[$i]}="
  # Create a working file expurged from the parameters
  egrep -ive '^$|^#' /etc/default/grub | egrep -ve "^${GRUB_PARAM}" | tee /etc/default/grub.tmp
  # Catch the last occurence to add it to the temp file
  egrep -e "${GRUB_PARAM}" /etc/default/grub | tail -1 | tee -a /etc/default/grub.tmp
  # Switch the temp file to the final file
  mv /etc/default/grub.tmp /etc/default/grub
done

