#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


set -eu

declare -a OPTIONS
OPTIONS=('install')
PYTHON=${DIB_PYTHON3:-python3}

if [ "${DISTRO_NAME}" == 'ubuntu' ]; then
  if [ "${DIB_RELEASE}" == "bionic" ]; then
    "${PYTHON}" -m pip install wheel
  fi
else
  if [ "${DIB_RELEASE}" != "7" ]; then
    OPTIONS=('install' '--prefix=/usr')
  fi 
fi

cd /opt/cloud-init
tar -zxvf "cloud-init.tgz"

cd "cloud-init-${DIB_CLOUD_INIT_VERSION}"

"${PYTHON}" -m pip install --upgrade pip
"${PYTHON}" -m pip "${OPTIONS[@]}" -r requirements.txt .
"${PYTHON}" setup.py "${OPTIONS[@]}" 
cd ..
rm -rf cloud-init-*

if [ -f /usr/local/bin/cloud-init ]; then
  mv /usr/local/bin/cloud-init /usr/bin
fi

if [ -f /usr/libexec/cloud-init/ds-identify ]; then
  mv /usr/libexec/cloud-init/ds-identify /usr/libexec/cloud-init/ds-identify.bak
fi
systemctl enable cloud-config
systemctl enable cloud-init
systemctl enable cloud-init-local
systemctl enable cloud-final
cat > /etc/cloud/cloud.cfg.d/91-cloud-init-datasources.cfg <<EOF
datasource_list: [ NoCloud, ConfigDrive, OpenStack, None ]
EOF

if [ "${DISTRO_NAME}" == 'opensuse' ]; then
  echo "Updating /etc/cloud/cloud.cfg"
  sed -i  's/distro: suse/distro: opensuse/g' /etc/cloud/cloud.cfg
fi

if [ "${DIB_NO_KANOD_NETWORK:-0}" = 1 ]; then
  exit 0
fi

if [ -d /etc/sysconfig/network-scripts ]; then
  rm -f /etc/sysconfig/network-scripts/ifcfg-*
fi

if [ -d /etc/NetworkManager/system-connections ]; then
  rm -f /etc/NetworkManager/system-connections/*
  systemctl disable NetworkManager
fi
