#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "${DISTRO_NAME}" == 'ubuntu' ]; then

  # Update cache
  apt update
  # Package software-properties-common provides add-apt-repository
  apt install -y software-properties-common
  # Add the Ubuntu openstack Antelope repo
  add-apt-repository cloud-archive:antelope
  # Install cloud-init package
  apt install -y cloud-init
  # Remove Ubuntu openstack Antelope repo
  add-apt-repository -r -y cloud-archive:antelope
  # Remove the tool
  apt remove --purge -y software-properties-common

  mv /etc/cloud/cloud.cfg.d/90_dpkg.cfg /etc/cloud/cloud.cfg.d/90_dpkg.cfg.orig

  # Replace the default Ubuntu user
  sed -i "s/name: ubuntu/name: ${DIB_CLOUD_INIT_DEFAULT_USERNAME}/" /etc/cloud/cloud.cfg
  sed -i "s/gecos: Ubuntu/gecos: ${DIB_CLOUD_INIT_DEFAULT_USERNAME}/" /etc/cloud/cloud.cfg
fi

if [ "${DISTRO_NAME}" == 'opensuse' ]; then

  # Install the cloud-init package from main repo
  zypper install -y cloud-init
  # Fix a bug in OpenSUSE package cloud-init-config-suse where the configuration
  # is not tailored for a SuSE OS but for Ubuntu one.
  # Minor version 71.1 containing the correct version
  zypper install --oldpackage -y cloud-init-config-suse=23.3-150100.8.71.1

  # Align distro
  sed -i "s/distro: sles/distro: opensuse/" /etc/cloud/cloud.cfg
  # Replace the default suse user
  sed -i "s/name: sles/name: ${DIB_CLOUD_INIT_DEFAULT_USERNAME}/" /etc/cloud/cloud.cfg
  sed -i "s/gecos: sles Cloud User/gecos: ${DIB_CLOUD_INIT_DEFAULT_USERNAME}/" /etc/cloud/cloud.cfg
fi

systemctl enable cloud-config
systemctl enable cloud-init
systemctl enable cloud-init-local
systemctl enable cloud-final

cat > /etc/cloud/cloud.cfg.d/91-cloud-init-datasources.cfg <<EOF
datasource_list: [ NoCloud, ConfigDrive, OpenStack, None ]
EOF

if [ "${DIB_NO_KANOD_NETWORK:-0}" = 1 ]; then
  exit 0
fi

if [ -d /etc/sysconfig/network-scripts ]; then
  rm -f /etc/sysconfig/network-scripts/ifcfg-*
fi

if [ -d /etc/NetworkManager/system-connections ]; then
  rm -f /etc/NetworkManager/system-connections/*
  systemctl disable NetworkManager
fi
