#!/bin/bash

set -eu

cd "/opt/tpm2-tss-${DIB_TPM2_TSS}"
./configure --prefix=/usr --disable-doxygen-doc
make -j
sudo make install

cd "/opt/tpm2-tools-${DIB_TPM2_TOOLS}"
./configure --prefix=/usr
make -j
sudo make install
