#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "$DISTRO_NAME" == "opensuse" ]; then
  echo "Unsupported distribution. A bug in element block-device-efi prevents EFI/SecureBoot."
  exit 1
fi

if type grub2-mkconfig >/dev/null; then
    GRUB_MKCONFIG="grub2-mkconfig"
else
    GRUB_MKCONFIG="grub-mkconfig"
fi
if [ -d /boot/grub2 ]; then
    GRUB_CFG=/boot/grub2/grub.cfg
    GRUBENV=/boot/grub2/grubenv
else
    GRUB_CFG=/boot/grub/grub.cfg
    GRUBENV=/boot/grub/grubenv
fi

# Remove GRUB_TERMINAL serial introduced by dib>bootloader>50-bootloader
# to prevent error message during the boot indicating serial module
# cannot be loaded.
sed -i "/GRUB_TERMINAL/s/serial //g" /etc/default/grub
$GRUB_MKCONFIG -o $GRUB_CFG

# Support only Debian style distro
if [[ ${DISTRO_NAME} =~ (ubuntu|debian) ]]; then
  apt install -y shim-signed grub-efi-amd64-signed
  update-grub
fi
