#!/bin/bash

if [ "$DISTRO_NAME" == "opensuse" ]; then
    if [ ! -f /usr/bin/mkinitrd ]; then
        echo "Replace mkinitrd by dracut on opensuse"
        echo -e '#!/bin/bash\ndracut --regenerate-all' > /usr/bin/mkinitrd
        chmod +x /usr/bin/mkinitrd
    fi
fi


