#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


set -eu

export LC_ALL

PYTHON=${DIB_PYTHON3:-python3}


if [ "$DISTRO_NAME" == "centos" ] && [ "$DIB_RELEASE" == "7" ]; then
    LC_ALL=en_US.UTF-8
else
    LC_ALL=C.UTF-8
fi

cd /opt/kanod-configure
mkdir -p kanod_configure/includes
cp -a "/tmp/in_target.d/config_includes/." kanod_configure/includes
cp /tmp/in_target.d/config_templates/*.tmpl kanod_configure/templates
"${PYTHON}" -m pip install . --break-system-packages

mkdir -p /etc/kanod-configure
touch /etc/kanod-configure/system.yaml
