#!/bin/bash
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


if [[ ! -f "/usr/bin/sylva-growparts" ]]; then
  >&2 echo -e "/usr/bin/sylva-growparts has not been created."
  exit 1
fi

systemctl enable sylva-growparts.service
