#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

if [ "$DISTRO_NAME" == "centos" ] && [ "$DIB_RELEASE" == "7" ]; then
    # There is not a rational reason why nginx is not installed by the
    # standard package-installs
    $YUM update -y
    $YUM install nginx -y
fi

systemctl disable nginx
cat > /etc/nginx/conf.d/proxy.conf <<EOF
proxy_send_timeout 120;
proxy_read_timeout 300;
proxy_buffering    off;
proxy_request_buffering off;
client_max_body_size  2000M;
EOF
