#!/bin/bash

#  Copyright (C) 2022 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


if [ -n "$DIB_PYPI_MIRROR_URL" ]; then
    echo '*** configuration of PIP mirror ***'
    PIP_MIRROR_HOST=$(echo "$DIB_PYPI_MIRROR_URL" | awk -F/ '{print $3}' | awk -F: '{print $1}')
    cat > /etc/pip.conf <<EOF
[global]
index=${DIB_PYPI_MIRROR_URL}/pypi
index-url=${DIB_PYPI_MIRROR_URL}/simple
trusted-host=${PIP_MIRROR_HOST}
EOF
fi
