#!/bin/bash

#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.


set -eu

tee /etc/modules-load.d/kubernetes.conf <<EOF
overlay
br_netfilter
EOF
tee /etc/sysctl.d/kubernetes.conf <<EOF
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

# this is based on https://v1-27.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm

K8S_VERSION=${K8S_VERSION%-*}  # remove the -... suffix
K8S_XY_VERSION=${K8S_VERSION%.*}  # remove the .z in x.y.z

# Support only Debian style distro
if [[ ${DISTRO_NAME} =~ (ubuntu) ]]; then

	echo "NOOP, as Canonical Kubernetes is installed via snapd by CK8s"
fi

