#  Copyright (C) 2020-2021 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

$schema: http://json-schema.org/draft-07/schema#
definitions:
  admin_user_definition:
    type: object
    description: Configuration of the admin user of the machine.
    additionalProperties: false
    properties:
      passwd:
        type: string
        description: optional password for admin user (do not use in production)
      keys:
        type: array
        items:
          type: string
          description: ssh public key accepted to log as admin user.
      username:
        description: optional username for admin user (default=admin)
        type: string
properties:
  admin:
    $ref: '#/definitions/admin_user_definition'
