#!/bin/bash

#  Copyright (C) 2023 Orange
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

tee /etc/sylva-diskimage-builder <<EOF
COMMIT_ID=${CI_COMMIT_SHA}
TAG=${CI_COMMIT_TAG}
K8S_VERSION=${K8S_VERSION}
FLAVOR=${FLAVOR}
HARDENED=${HARDENED}
K8S_FLAVOR=${K8S_FLAVOR}
PIPELINE_ID=${CI_PIPELINE_ID}
PIPELINE_URL=${CI_PIPELINE_URL}
JOB_ID=${CI_JOB_ID}
JOB_URL=${CI_JOB_URL}
EOF
