options:
- name: debug
  kind: var
- name: tpm
  kind: flag
- name: cloud_init_version
  kind: var
  default: '23.1'
- name: target
  default: ubuntu
  choices:
  - ubuntu
  - centos
  - opensuse
  kind: var
- name: image_size
  kind: var
- name: packages
  kind: var
- name: release
  default: bionic
  kind: var
- name: lvm
  kind: flag
- name: cis_remediation
  kind: flag
- name: cis_remediation_opensuse
  kind: flag
- name: rename_interface_names
  kind: flag
- name: grub_config
  kind: flag
- name: image
  kind: var
- name: no_kanod_network
  kind: flag
- name: kanod_admin
  kind: flag
- name: growpart
  kind: flag
- name: rke2_airgapped
  kind: flag
- name: kubeadm
  kind: flag

env:
- name: DIB_TPM2_TOOLS
  value: "5.2"
- name: DIB_TPM2_TSS
  value: "2.4.6"
- name: DIB_PYVER
  value: "3.8.13"
- name: OVERWRITE_OLD_IMAGE
  value: '1'
- name: DIB_DEV_USER_PWDLESS_SUDO
  value: 'yes'
  when:
  - debug
- name: DIB_DEV_USER_PASSWORD
  value: '{{debug}}'
  when:
  - debug
- name: DIB_DEV_USER_SHELL
  value: /bin/bash
  when:
  - debug
- name: DIB_LOCAL_IMAGE
  value: '{{image}}'
  when:
  - image
  - '!image=-'
- name: DIB_IMAGE_SIZE
  value: '{{image_size}}'
  when:
  - image_size
- name: DIB_CLOUD_INIT_DEFAULT_USERNAME
  value: 'node-admin'
- name: DIB_CLOUD_INIT_ETC_HOSTS
  value: 'true'
- name: DIB_CLOUD_INIT_DATASOURCES
  value: 'NoCloud'
- name: DIB_YUM_MINIMAL_CREATE_INTERFACES
  value: '0'
- name: DIB_RELEASE
  when:
  - target=ubuntu
  value: '{{release | default("bionic")}}'
- name: DIB_RELEASE
  when:
  - target=centos
  value: '{{release | default("8")}}'
- name: DIB_RELEASE
  when:
  - target=opensuse
  value: '{{release | default("15.6")}}'
- name: DIB_BOOTLOADER_DEFAULT_CMDLINE
  value: 'nofb nomodeset gfxpayload=text net.ifnames=1'
  when:
  - target=centos
- name: DIB_KANOD_ROLE
  value: core
- name: DIB_KANOD_LIBRARIES
  value: ''
- name: DIB_PYTHON3
  value: python3.8
  when:
  - 'target=centos'
  - 'release=7'
- name: DIB_PYTHON3
  value: python3.8
  when:
  - 'target=centos'
  - 'release=8-stream'
- name: DIB_PYTHON3
  value: python3.8
  when:
  - 'target=ubuntu'
  - 'release=bionic'
- name: DIB_PYTHON3
  value: python3.11
  when:
  - 'target=opensuse'
- name: YUM
  value: dnf
  when:
  - 'target=centos'
  - '!release=7'
- name: DIB_BOOTLOADER_DEFAULT_CMDLINE
  value: 'nofb nomodeset gfxpayload=text net.ifnames=1'
  when:
  - target=opensuse
- name: DIB_NO_KANOD_NETWORK
  value: '1'
  when:
  - no_kanod_network

recipes:
- elements:
  - kanod-mirror
  - kanod-cloud-init
  - kanod-admin
  - vm
  - openssh-server
  - runtime-ssh-host-keys
  - bootloader
  - grub-init
  - kanod-configure
  - chrony
  - build-info
  - fix-secureboot
  - gtp5g
  - sylva-group
- when:
  - tpm
  elements:
  - tpm2tools
- when:
  - grub_config
  elements:
  - grub-config
- when:
  - target=ubuntu
  packages:
  - initramfs-tools
  - parted
  - kbd
  - lvm2
  - netplan.io
  - cryptsetup
  - less
  - tuned
  - jq
  - nfs-common
  elements:
  - ubuntu{{ "" if image is defined else "-minimal" }}
  - ubuntu-fix
  - klvm
- when:
  - debug
  elements:
  - devuser
- when:
  - target=ubuntu
  - debug
  packages:
  - vim
  - tcpdump
  - nmap
  - iputils-ping
  - python3-setuptools
  - cryptsetup
- when:
  - target=centos
  packages:
  - epel-release
  - openssh-clients
  elements:
  - centos{{ "" if image is defined else "-minimal" }}
  - yum
  - selinux-permissive
- when:
  - target=centos
  - '!release=9-stream'
  packages:
  - network-scripts
- when:
  - target=centos
  - debug
  packages:
  - nmap
  - python3-setuptools
- when:
  - packages
  packages:
  - '{{packages}}'
- when:
  - target=ubuntu
  - cis_remediation
  packages:
  - git
  elements:
  - cis-remediation
- when:
  - target=ubuntu
  - release=jammy
  packages:
  - vim
  - iputils-ping
  - rsyslog
  - nfs-common
  - iptables
  - cryptsetup
- when:
  - target=ubuntu
  - rename_interface_names
  elements:
  - rename-interface-names
- when:
  - target=centos
  packages:
  - gdisk
  elements:
  - block-device-gpt
- when:
  - target=centos
  - release=7
  elements:
  - python38
  packages:
  - dhclient
- when:
  - target=opensuse
  packages:
  - python311-base
  - python311-devel
  - python311-pip
  - python311-setuptools
  - virtme
  - parted
  - kbd
  - lvm2
  - gptfdisk
  - iproute2
  - nginx
  - apparmor-utils
  - conntrack-tools
  - conntrackd
  - bind-utils
  - chrony
  - patch
  - curl
  - gcc
  - iptables
  - cryptsetup
  - tuned
  - jq
  - wicked
  - wicked-service
  - vim
  - nfs-client
  - kernel-firmware-network
  elements:
  - opensuse{{ "" if image is defined else "-minimal" }}
  - opensuse-fix
- when:
  - target=opensuse
  - cis_remediation_opensuse
  elements:
  - cis-remediation-opensuse
- when:
  - target=ubuntu
  - kanod_admin
  elements:
  - kanod-admin
- when:
  - growpart
  elements:
  - cloud-init-growpart
- when:
  - rke2_airgapped
  elements:
  - rke2-airgapped
- when:
  - kubeadm
  elements:
  - kubeadm
- when:
  - '!lvm'
  elements:
  - block-device-efi
- when:
  - lvm
  - rke2_airgapped
  elements:
  - block-device-rke2-lvm
- when:
  - lvm
  - kubeadm
  elements:
  - block-device-kubeadm-lvm
