---
include:
  - local: .gitlab/ci/templates-build-tests.yml

workflow:
  rules:
    - when: always

stages:
  - build
  - boot-image
  - generate-sbom
  - promote-image
  - scan-image
  - publish-report

build-image:
  stage: build
  extends: .build-image

boot-image:
  stage: boot-image
  extends: .boot-image
  parallel:
    matrix:
      - VM_BOOT_MODE:
          - legacy
          - uefi

generate-sbom:
  stage: generate-sbom
  extends: .generate-sbom

promote:
  stage: promote-image
  extends: .promote-image

openscap-scan:
  stage: scan-image
  extends: .openscap-scan

upload-report:
  stage: publish-report
  extends: .publish-scan
