---
include:
  - local: .gitlab/ci/templates-build-tests.yml

workflow:
  rules:
    - when: always

stages:
  - build
  - boot-image
  - scan-image
  - promote-image
  - publish-report

build-image:
  stage: build
  extends: .build-image-suse

boot-image:
  stage: boot-image
  extends: .boot-image
  parallel:
    matrix:
      - VM_BOOT_MODE:
          - legacy
          - uefi

generate-sbom:
  stage: scan-image
  extends: .generate-sbom

openscap-scan:
  stage: scan-image
  extends: .openscap-scan
  needs:
    - generate-sbom

openscap-scan-opensuse-oval:
  stage: scan-image
  extends: .openscap-scan-opensuse-oval
  needs:
    - generate-sbom

promote:
  stage: promote-image
  extends: .promote-image


upload-report:
  stage: publish-report
  extends: .publish-scan
