---
include:
  - local: .gitlab/ci/templates-build-tests.yml

workflow:
  rules:
    - when: always

stages:
  - build
  - boot-image
  - promote-image

build-image:
  stage: build
  extends: .build-image-suse

boot-image:
  stage: boot-image
  extends: .boot-image
  parallel:
    matrix:
      - VM_BOOT_MODE:
          - legacy
          # UEFI is disabled due to a bug with diskimage-builder
          # https://gitlab.com/sylva-projects/sylva-elements/diskimage-builder/-/issues/47
          #- uefi

promote:
  stage: promote-image
  extends: .promote-image
